development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  database: myapp_production
  username: ricardo
  password: iop123
  port: 5432
