development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['myapp_production']%>
  pool: 5
  username: <%= ENV['myapp'] %>
  password: <%= ENV['DATEBASE_PASSWORD'] %>
  host: <%= ENV['DATEBASE_HOST'] %>
